version: '3.8'

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    platform: linux/amd64  # Specify platform
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    platform: linux/amd64  # Specify platform
    ports:
      - "2181:2181"

  rabbitmq:
    image: rabbitmq:3-management
    platform: linux/amd64  # Specify platform
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
